### ISSUE TITLE
Redux store gets only the preview element not the other.

### ISSUE THREAD

**Issue by GautierT** [BBB/dropzone-redux-form-example#6]
Hi @BBB, 
Thanks for your exemple ! Working great.
But i wondering why in my redux store i have only the `preview` element and not the others elements.

Redux devtools :  
![image](https://cloud.githubusercontent.com/assets/6089653/20758795/338f8110-b71b-11e6-9d48-c979b63ab03f.png)

The file in the Chrome dev console
![image](https://cloud.githubusercontent.com/assets/6089653/20758804/3af4a9e4-b71b-11e6-99b7-15e7ea948663.png)

Thanks for your help

**Comment by GautierT** [comment]
When i do like this
```
onDrop={(filesToUpload, e) => {
    console.log('filesToUpload : ', filesToUpload);
    props.input.onChange(
        filesToUpload.map(file => {
            return {
                name : file.name,
                preview : file.preview
            }
        })
    )
}}
```
it's working so i guess its's the `file` type that redux does'n't like !

**Comment by BBB** [comment]
This is likely to do with the way that redux dev tools iterates the properties of the `File` object. I think the object will still be stored correctly.

I'm glad to see you found a workaround!
