### ISSUE TITLE
Empty FormData object

### ISSUE THREAD

**Issue by kaueburiti** [BBB/dropzone-redux-form-example#7]
I have cloned the project and when i run in my browser, the `console.info('POST', body, data);` at line 40 (`App.js`) just shows a empty FormData. Is that normal?

**Comment by aindong** [comment]
Im also having an empty formdata object

**Comment by BBB** [comment]
@kaueburiti If you POST to your server, does it send the contents? 

I think this is just an issue with how your browser shows FormData in the console [See this StackOverflow for more info](http://stackoverflow.com/questions/25040479/formdata-created-from-an-existing-form-seems-empty-when-i-log-it).
