### ISSUE TITLE
No Preview Displayed

### ISSUE THREAD

**Issue by crustyratfink** [BBB/dropzone-redux-form-example#8]
Integrating with Rails, I've copied this example as-is, and I'm getting the data, but there's no feedback (progress) or preview displayed. Could you shed any light on why that might be the case? 

If I modify the example to add `<img src={file.preview} />` when the uploaded file is listed, it shows up, but that's not the expected default behavior, is it?

Not including code only because it's exactly what you have here... except in a Rails context (i.e., the component is served up as a view). I suspect I'm just having a mental disconnect between Dropzone and dropzone.js in terms of configurability.

**Comment by BBB** [comment]
The example, just shows you how you can access the files dropped onto the dropzone, and how to process them on submit. It makes no assumptions about how previews are displayed. That's entirely up to you.

It sounds like you're doing the right thing.
